### ISSUE TITLE
Failing on dnadesign/silverstripe-elemental but passes locally

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-update-js#23]
16 tests fail when gha-update-js is run against the dnadesign/silverstripe-elemental repository.
Failures look like this:
> FAIL client/src/components/ElementEditor/tests/Header-test.js
>  ● Test suite failed to run
>
>    TypeError: (0 , _jestUtil.invariant) is not a function
>      at eventHandler (node_modules/jest-circus/build/eventHandler.js:248:31)

These tests pass fine locally.

## Possible causes:
- different npm version
- different yarn version
- ???

## Additional output that gha-update-js should give us that might help debugging this sort of thing:
- yarn version and npm version clearly near the top or bottom of the full run
- include package.json and package.lock in artifacts

## Failed PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1087
- https://github.com/silverstripe/silverstripe-elemental/pull/1088 (manual replacement of 1087)
- https://github.com/silverstripe/gha-update-js/pull/25
- https://github.com/silverstripe/silverstripe-elemental/pull/1097

**Comment by emteknetnz** [comment]
update-js workflow magincally started working again on elemental, have linked PR

Have created another PR on gha-update-js to output version numbers of node, npm and yarn and also adding package.json and yarn.lock to artifacts

**Comment by GuySartorelli** [comment]
Weird that it's working now but hey at least that's less time spent debugging. Good to have those extra datapoints for next time too.
PRs merged. Closing.
