### ISSUE TITLE
Replace ci-cd-js with gha-update-js

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-update-js#5]
Replace https://github.com/silverstripe/github-actions-ci-cd/blob/main/.github/workflows/update-js-deps.yml with gha-update-js

Note that the old ci-cd was not deleting old branches (though it is deleteting old pull-requests ok) https://github.com/silverstripe/silverstripe-campaign-admin/pull/224#issuecomment-1179521781

### PRs
- https://github.com/silverstripe/silverstripe-cms/pull/2757
- https://github.com/silverstripe/silverstripe-mfa/pull/461
- https://github.com/silverstripe/silverstripe-blog/pull/681
- https://github.com/silverstripe/silverstripe-admin/pull/1330
- https://github.com/silverstripe/silverstripe-comments/pull/344
- https://github.com/silverstripe/silverstripe-tagfield/pull/216
- https://github.com/silverstripe/silverstripe-userforms/pull/1160
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1284
- https://github.com/silverstripe/silverstripe-login-forms/pull/119
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/271
- https://github.com/silverstripe/silverstripe-contentreview/pull/167
- https://github.com/silverstripe/silverstripe-frameworktest/pull/113
- https://github.com/silverstripe/silverstripe-segment-field/pull/68
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/236
- https://github.com/silverstripe/silverstripe-session-manager/pull/116
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/244
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/171
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/96
- https://github.com/silverstripe/silverstripe-elemental/pull/994
- https://github.com/silverstripe/silverstripe-security-extensions/pull/45
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/90
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/116
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/465

**Comment by GuySartorelli** [comment]
PRs merged
